name: Build and Export Docker Image
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          # 構建鏡像並命名為 my_env:latest
          docker build -t my_env:latest .
          
          # 將鏡像導出為 tar 壓縮包
          docker save my_env:latest > my_env_image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-bundle
          path: my_env_image.tar
