name: Download Docker Image

on:
  workflow_dispatch: # 允許手動點擊執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Docker Image
        run: |
          # 拉取你需要的 ROS 鏡像
          docker pull osrf/ros:noetic-desktop-full
          
          # 將鏡像保存為 tar 檔案
          docker save osrf/ros:noetic-desktop-full -o ros_noetic.tar
          
          # 壓縮以減小下載體積
          gzip ros_noetic.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ros-image-tar
          path: ros_noetic.tar.gz
          retention-days: 1 # 下載連結保留 1 天
